### ISSUE TITLE
Email Settings page is empty with console error after updating to v5.13

### ISSUE THREAD

**Issue by silent-sphinx** [invoiceninja/ui#3386]
### Invoice Ninja version

v5.13

### Environment

Docker

### Interface

React

### Can you reproduce the issue on one of our demo sites?

No

### Pre-flight checks

- [x] I have reviewed the troubleshooting documentation.
- [x] I have searched existing issues for duplicates.

### Have you reported this issue on Slack or the forum?

No

### Have you inspected the application logs?

Yes, but I found no relevant errors

### Describe the bug

When visiting the React page of my self-hosted docker Invoice Ninja instance, after upgrading to v5.13 the 'Email Settings' page is completely blank, no other pages experience this issue. See screenshot. There are a number of errors in the Developer Console, see the relevant errors below the image.

<img width="1920" height="983" alt="Image" src="https://github.com/user-attachments/assets/bee080b2-7134-4d3a-a4d0-e549ca4e1acd" />

```
Error with Permissions-Policy header: Unrecognized feature: 'private-aggregation'.
Error with Permissions-Policy header: Unrecognized feature: 'attribution-reporting'.
email_settings:164  GET https://static.cloudflareinsights.com/beacon.min.js/v31edd6df95cf4e85bb4c19e7a9bdbcba1788362987495 net::ERR_BLOCKED_BY_CLIENT
forms-DEWnBS77.js:8 TypeError: (e || "").trim is not a function
    at lj (src-BqcBxT8m.js:448:120974)
    at VDe (src-BqcBxT8m.js:448:121347)
    at HDe (src-BqcBxT8m.js:448:121939)
    at ZDe (src-BqcBxT8m.js:448:127826)
    at $De (src-BqcBxT8m.js:448:130568)
    at zo (forms-DEWnBS77.js:6:16885)
    at K (forms-DEWnBS77.js:8:43774)
    at Bl (forms-DEWnBS77.js:8:39553)
    at Rl (forms-DEWnBS77.js:8:39481)
    at Ll (forms-DEWnBS77.js:8:39336)
Ms @ forms-DEWnBS77.js:8
Ps.n.callback @ forms-DEWnBS77.js:8
mo @ forms-DEWnBS77.js:6
Hc @ forms-DEWnBS77.js:8
Vc @ forms-DEWnBS77.js:8
Bc @ forms-DEWnBS77.js:8
Ul @ forms-DEWnBS77.js:8
Hl @ forms-DEWnBS77.js:8
wl @ forms-DEWnBS77.js:8
x @ forms-DEWnBS77.js:1
ne @ forms-DEWnBS77.js:1
postMessage
re @ forms-DEWnBS77.js:1
ie @ forms-DEWnBS77.js:1
e.unstable_scheduleCallback @ forms-DEWnBS77.js:1
Zl @ forms-DEWnBS77.js:8
Ul @ forms-DEWnBS77.js:8
Hl @ forms-DEWnBS77.js:8
kl @ forms-DEWnBS77.js:8
ha @ forms-DEWnBS77.js:6
(anonymous) @ forms-DEWnBS77.js:8
XMLHttpRequest.send
(anonymous) @ forms-DEWnBS77.js:205
xhr @ forms-DEWnBS77.js:205
yf @ forms-DEWnBS77.js:207
_request @ forms-DEWnBS77.js:208
request @ forms-DEWnBS77.js:207
(anonymous) @ forms-DEWnBS77.js:203
xh @ forms-DEWnBS77.js:209
queryFn @ src-BqcBxT8m.js:567
i @ forms-DEWnBS77.js:1
_ @ forms-DEWnBS77.js:1
start @ forms-DEWnBS77.js:1
fetch @ forms-DEWnBS77.js:1
fetchQuery @ src-BqcBxT8m.js:2
Tq @ src-BqcBxT8m.js:567
Eq @ src-BqcBxT8m.js:567
zo @ forms-DEWnBS77.js:6
K @ forms-DEWnBS77.js:8
Bl @ forms-DEWnBS77.js:8
Rl @ forms-DEWnBS77.js:8
Ll @ forms-DEWnBS77.js:8
wl @ forms-DEWnBS77.js:8
x @ forms-DEWnBS77.js:1
ne @ forms-DEWnBS77.js:1
postMessage
re @ forms-DEWnBS77.js:1
ie @ forms-DEWnBS77.js:1
e.unstable_scheduleCallback @ forms-DEWnBS77.js:1
Zl @ forms-DEWnBS77.js:8
Cl @ forms-DEWnBS77.js:8
Sl @ forms-DEWnBS77.js:8
fu @ forms-DEWnBS77.js:8
yu.render.vu.render @ forms-DEWnBS77.js:8
Ett @ src-BqcBxT8m.js:661
await in Ett
(anonymous) @ src-BqcBxT8m.js:661
PendingScript
t.activateScript @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
t.run @ rocket-loader.min.js:1
P @ rocket-loader.min.js:1
callback @ rocket-loader.min.js:1
t.run @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
forms-DEWnBS77.js:8 Uncaught TypeError: (e || "").trim is not a function
    at lj (src-BqcBxT8m.js:448:120974)
    at VDe (src-BqcBxT8m.js:448:121347)
    at HDe (src-BqcBxT8m.js:448:121939)
    at ZDe (src-BqcBxT8m.js:448:127826)
    at $De (src-BqcBxT8m.js:448:130568)
    at zo (forms-DEWnBS77.js:6:16885)
    at K (forms-DEWnBS77.js:8:43774)
    at Bl (forms-DEWnBS77.js:8:39553)
    at Rl (forms-DEWnBS77.js:8:39481)
    at Ll (forms-DEWnBS77.js:8:39336)
lj @ src-BqcBxT8m.js:448
VDe @ src-BqcBxT8m.js:448
HDe @ src-BqcBxT8m.js:448
ZDe @ src-BqcBxT8m.js:448
$De @ src-BqcBxT8m.js:448
zo @ forms-DEWnBS77.js:6
K @ forms-DEWnBS77.js:8
Bl @ forms-DEWnBS77.js:8
Rl @ forms-DEWnBS77.js:8
Ll @ forms-DEWnBS77.js:8
Tl @ forms-DEWnBS77.js:8
wl @ forms-DEWnBS77.js:8
x @ forms-DEWnBS77.js:1
ne @ forms-DEWnBS77.js:1
postMessage
re @ forms-DEWnBS77.js:1
ie @ forms-DEWnBS77.js:1
e.unstable_scheduleCallback @ forms-DEWnBS77.js:1
Zl @ forms-DEWnBS77.js:8
Ul @ forms-DEWnBS77.js:8
Hl @ forms-DEWnBS77.js:8
kl @ forms-DEWnBS77.js:8
ha @ forms-DEWnBS77.js:6
(anonymous) @ forms-DEWnBS77.js:8
XMLHttpRequest.send
(anonymous) @ forms-DEWnBS77.js:205
xhr @ forms-DEWnBS77.js:205
yf @ forms-DEWnBS77.js:207
_request @ forms-DEWnBS77.js:208
request @ forms-DEWnBS77.js:207
(anonymous) @ forms-DEWnBS77.js:203
xh @ forms-DEWnBS77.js:209
queryFn @ src-BqcBxT8m.js:567
i @ forms-DEWnBS77.js:1
_ @ forms-DEWnBS77.js:1
start @ forms-DEWnBS77.js:1
fetch @ forms-DEWnBS77.js:1
fetchQuery @ src-BqcBxT8m.js:2
Tq @ src-BqcBxT8m.js:567
Eq @ src-BqcBxT8m.js:567
zo @ forms-DEWnBS77.js:6
K @ forms-DEWnBS77.js:8
Bl @ forms-DEWnBS77.js:8
Rl @ forms-DEWnBS77.js:8
Ll @ forms-DEWnBS77.js:8
wl @ forms-DEWnBS77.js:8
x @ forms-DEWnBS77.js:1
ne @ forms-DEWnBS77.js:1
postMessage
re @ forms-DEWnBS77.js:1
ie @ forms-DEWnBS77.js:1
e.unstable_scheduleCallback @ forms-DEWnBS77.js:1
Zl @ forms-DEWnBS77.js:8
Cl @ forms-DEWnBS77.js:8
Sl @ forms-DEWnBS77.js:8
fu @ forms-DEWnBS77.js:8
yu.render.vu.render @ forms-DEWnBS77.js:8
Ett @ src-BqcBxT8m.js:661
await in Ett
(anonymous) @ src-BqcBxT8m.js:661
PendingScript
t.activateScript @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
t.run @ rocket-loader.min.js:1
P @ rocket-loader.min.js:1
callback @ rocket-loader.min.js:1
t.run @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
```

### Steps to reproduce

1. `sudo docker pull invoiceninja/invoiceninja-debian:5.13`
2. `sudo docker compose up -d`
3. Visit 'Email Settings' Page

### Expected behavior

The Email Settings page to be visible.

### Additional context

Hosted via docker compose on debian, invoice ninja is delivered via `cloudflared` tunnel as a reverse proxy to a custom web domain.

### Relevant log output

```shell
2026-09-14T18:43:38.923781737Z 10.200.12.8 -  14/Sep/2026:18:43:38 +0000 "GET /index.php" 200

2026-09-14T18:43:39.643499198Z 10.200.12.8 -  14/Sep/2026:18:43:39 +0000 "GET /index.php" 200

2026-09-14T18:43:39.693898686Z 10.200.12.8 -  14/Sep/2026:18:43:39 +0000 "POST /index.php" 200

2026-09-14T18:43:39.928149930Z 10.200.12.8 -  14/Sep/2026:18:43:39 +0000 "GET /index.php" 200

2026-09-14T18:43:39.933790867Z 10.200.12.8 -  14/Sep/2026:18:43:39 +0000 "GET /index.php" 200

2026-09-14T18:43:40.007895483Z 10.200.12.8 -  14/Sep/2026:18:43:39 +0000 "GET /index.php" 200

2026-09-14T18:43:40.096933899Z 10.200.12.8 -  14/Sep/2026:18:43:39 +0000 "POST /index.php" 200

2026-09-14T18:43:40.780169560Z 10.200.12.8 -  14/Sep/2026:18:43:39 +0000 "GET /index.php" 200

2026-09-14T18:43:43.724344460Z 127.0.0.1 -  14/Sep/2026:18:43:43 +0000 "GET " 200
```

**Comment by turbo124** [comment]
I cannot recreate this. My guess is your environment.

```
Error with Permissions-Policy header: Unrecognized feature: 'private-aggregation'.
Error with Permissions-Policy header: Unrecognized feature: 'attribution-reporting'.
email_settings:164  GET https://static.cloudflareinsights.com/beacon.min.js/v31edd6df95cf4e85bb4c19e7a9bdbcba1788362987495 net::ERR_BLOCKED_BY_CLIENT
```

These headers are cloudflare, and may be related to an issue downloading resources related to the wysiwyg signature editor on that particular page.

**Comment by AndyRap** [comment]
Hi,

I am experiencing a similar issue with the email settings page not displaying too, with v5.13.40. I have tried both through my URL and, by accessing the container IP directly, thereby bypassing DNS / Traefik / Crowdsec or any other third party software that may be hindering the connection.

<img width="939" height="1001" alt="Image" src="https://github.com/user-attachments/assets/d313b074-a39b-4d70-ae5d-d649f3287e31" />

Thanks

**Comment by silent-sphinx** [comment]
I believe I've identified the likely root cause, I'm not familiar with this codebase though and I'm just trying to diagnose this fault for a client.

You raised that `static.cloudflareinsights.com/beacon.min.js` being blocked by the client could be the error, this is Cloudflare's Web Analytics/RUM script likely being blocked by an network-wide adblocker and unrelated to Invoice Ninja's functionality. This is due to Invoice Ninja being delivered via Cloudflare Access/Cloudflared. It appears @AndyRap isn't using Cloudflare and is encountering the same error which would rule this out.

I cloned invoiceninja/ui (the React frontend repo) and traced this to `src/pages/settings/email-settings/common/components/SMTPMailDriver.tsx`, line 63:

```tsx
<Element leftSide={t('port')} leftSideHelp={t('port_help')}>
  <InputField
    value={company?.smtp_port || ''}
    onValueChange={(value) => handleChange('smtp_port', value)}
    disabled={isFormBusy}
  />
</Element>
```

Every other field in this same component (`smtp_host`, `smtp_encryption`, `smtp_username`, `smtp_password`, `smtp_local_domain`) is guarded with `|| ''` to force a string. `smtp_port` has the same guard, but since my `smtp_port` value is 2525, a JSON number, not a string, the `|| ''` fallback never triggers, and 2525 gets handed to InputField as-is.

I confirmed this by pulling my raw company settings via the API (GET `/api/v1/companies/{id}`). Relevant excerpt:

```json
"smtp_host": "smtp-bridge",
"smtp_port": 2525,
"smtp_encryption": "",
"smtp_username": "********",
"smtp_password": "********",
"smtp_local_domain": "",
"smtp_verify_peer": false,
```

Every other SMTP field is a string (even when empty, ""). `smtp_port` is the sole numeric field in this set; and it's the one field on this exact page without a `|| ''` guard that actually applies. That lines up with the error only affecting Email Settings and not reproducing on your demo sites (which presumably have smtp_port stored as a string, or unset entirely).

I could be wrong in thinking this is the potential error, appreciate your thoughts on this. Thank you.

**Comment by CNC-at-Home** [comment]
I can confirm that the `smtp_port` type is the cause of the white screen on the Email Settings page.

I am running **Invoice Ninja 5.13.40** (self-hosted).

**Root cause**

In my database, the `companies.smtp_port` column is defined as:
`smtp_port int(10) unsigned`

Therefore, when an SMTP port such as `465` is returned to the frontend, it is a number, not a string.

I was able to reproduce the problem very reliably:

> `smtp_port = NULL` → Email Settings page loads normally
> `smtp_port = 465` → Email Settings page immediately becomes completely white
> Sending a test email with port `465` works successfully, so this is **not an SMTP connectivity or configuration problem**

The browser console showed:
`TypeError: (e || "").trim is not a function`

**Frontend code causing the problem**

I traced this to the generated frontend code in `src-BqcBxT8m.js`.

The relevant function is:
`lj=e=>(e||``).trim()`
And `VDe()` calls this function directly with the SMTP port:
`lj(e.smtp_port)`

Since `smtp_port` is a numeric value (`465`), `.trim()` does not exist and the frontend crashes.

This also explains why the problem only occurs on the Email Settings page and why the page becomes completely blank without producing a Laravel/PHP error.

**Tested fix**

I changed the function to explicitly convert the value to a string:
`lj=e=>(e==null?``:String(e)).trim()`

After applying this change:

> the Email Settings page loads correctly with port `465`
> port `465` can be saved normally
> the page remains functional after reloading
> the SMTP test email is sent successfully
> 

**Conclusion**
This confirms the suspected root cause described above: `smtp_port` is correctly stored as an integer by the backend/database, but the frontend code assumes that the value is always a string and calls `.trim()` on it.

The frontend should therefore either normalize `smtp_port` to a string before passing it to `trim()`, or otherwise handle the numeric value explicitly.

The fix above resolves the issue without changing the database schema or storing the SMTP port as a string.

**Comment by turbo124** [comment]
I understand the issue here. Only reveals when transport is set to SMTP. checking in a fix.
